name: win-debug

on:
  workflow_dispatch:
    inputs:
      cpu:
        description: "Target architecture"
        required: true
        type: choice
        options: [x64, arm64]
        default: x64
      self_contained:
        description: "Include .NET runtime (self-contained)?"
        required: true
        type: boolean
        default: true
      win_app_sdk_self_contained:
        description: "Bundle Windows App SDK self-contained?"
        required: true
        type: boolean
        default: true

jobs:
  build-debug:
    runs-on: windows-2025

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Restore
        working-directory: ./src
        run: dotnet restore SyncClipboard.WinUI3

      - name: Build SyncClipboard.WinUI3 (Debug)
        run: >
          msbuild
          src\SyncClipboard.WinUI3\SyncClipboard.WinUI3.csproj
          /p:Platform=${{ inputs.cpu }}
          /p:RuntimeIdentifier=win-${{ inputs.cpu }}
          /p:Configuration=Debug
          /p:WindowsAppSDKSelfContained=${{ inputs.win_app_sdk_self_contained }}
          /p:SelfContained=${{ inputs.self_contained }}
          /v:m -restore

      - name: Copy output
        run: >
          xcopy
          src\SyncClipboard.WinUI3\bin\${{ inputs.cpu }}\Debug\net9.0-windows10.0.19041.0\win-${{ inputs.cpu }}
          WinUI3\
          /s /e

      - name: Set update info
        shell: bash
        run: |
          chmod +x ./build/SetUpdateSource.sh
          ./build/SetUpdateSource.sh -m manual -s github -o WinUI3 -n SyncClipboard_win_${{ inputs.cpu }}_Debug

      - name: Zip portable Debug build
        shell: bash
        run: |
          7z a SyncClipboard_win_${{ inputs.cpu }}_portable_Debug.zip ./WinUI3/*

      - name: Upload artifact (zip)
        uses: actions/upload-artifact@v4
        with:
          name: SyncClipboard_win_${{ inputs.cpu }}_portable_Debug
          path: SyncClipboard_win_${{ inputs.cpu }}_portable_Debug.zip
