name: build-pr

on:
  pull_request:

jobs:
  code-style:
    uses: ./.github/workflows/code-style.yml

  prebuild:
    uses: ./.github/workflows/prebuild.yml
    with:
      checkout-repo: ${{ github.repository }}
      checkout-ref: ${{ github.ref }}

  build-win:
    uses: ./.github/workflows/win-build.yml
    needs: prebuild
